import { parse } from "yaml"
import { describe, expect, it } from "vitest"

import { adaptiveLogsInstructions, compileAdaptiveLogs } from "@/lib/core/logs/compile/adaptive-logs"
import { compileAlloyLogs } from "@/lib/core/logs/compile/alloy"
import { commentText, formatBytesIEC } from "@/lib/core/logs/compile/common"
import { compileLokiLimits } from "@/lib/core/logs/compile/loki-limits"
import { compilePromtailLogs } from "@/lib/core/logs/compile/promtail"
import { parseAlloyBlocks, parseAlloyLogs } from "@/lib/core/logs/parse/alloy"
import { durationHours, parseLokiLimits } from "@/lib/core/logs/parse/loki-limits"
import { parsePromtailLogs } from "@/lib/core/logs/parse/promtail"
import { createLogRule, logRuleKey, type LogRuleInput } from "@/lib/core/logs/rules"
import type { LabelMatcher, LogRule, StreamSelector } from "@/lib/core/logs/types"

// lib/sources needs DOM types the test (worker) project lacks: load it at runtime.
interface AdaptiveLogsSource {
  adaptiveLogsBaseUrl(baseUrl: string): string | null
  recommendationPattern(recommendation: { tokens: string[] }): string
}
const adaptiveLogsPath = "@/lib/sources/adaptive-logs"
const loadAdaptiveLogs = async () => (await import(/* @vite-ignore */ adaptiveLogsPath)) as AdaptiveLogsSource

const now = new Date("2026-09-26T12:00:00Z")
const sel = (...matchers: Array<[string, LabelMatcher["op"], string]>): StreamSelector => ({
  matchers: matchers.map(([label, op, value]) => ({ label, op, value })),
})
const app = sel(["app", "=", "api"])

function rule(input: Partial<LogRuleInput> & Pick<LogRuleInput, "kind">): LogRule {
  return createLogRule({ selector: app, origin: "user", ...input } as LogRuleInput)
}

/** One rule of every collector kind, with awkward values. */
function collectorRules(): LogRule[] {
  return [
    rule({ kind: "drop_streams", selector: sel(["app", "=", 'say "hi"\\x'], ["env", "=~", "dev|test"]) }),
    rule({ kind: "drop_lines", line: { regex: 'GET /health(z)? "ok"\\s+\\d{3}' } }),
    rule({ kind: "drop_lines", selector: sel(["app", "=", "worker"]), line: { levels: ["trace", "debug"] } }),
    rule({ kind: "sample", selector: sel(["app", "=", "web"]), keep: 0.25 }),
    rule({ kind: "sample", selector: sel(["app", "=", "web"], ["path", "!=", "/x"]), line: { regex: "cache (hit|miss)" }, keep: 0.1 }),
    rule({ kind: "sample", selector: sel(["app", "=", "batch"]), line: { levels: ["info"] }, keep: 0.5 }),
    rule({ kind: "drop_label", label: "pod" }),
    rule({ kind: "drop_label", selector: sel(), label: "node_name" }),
    rule({ kind: "label_to_metadata", selector: sel(["namespace", "=", "prod"]), label: "trace_id" }),
    rule({ kind: "drop_lines", selector: sel(), line: { regex: "^$" } }),
  ]
}

const keys = (rules: LogRule[]) => rules.map(logRuleKey).sort()
const settings = (rules: LogRule[]) =>
  rules
    .map((r) => [logRuleKey(r), r.kind === "sample" ? r.keep : r.kind === "retention" ? r.days : null])
    .sort((a, b) => String(a[0]).localeCompare(String(b[0])))

describe("Alloy loki.process export", () => {
  it("renders a cardinal component with header, rationale and savings", () => {
    const withImpact = {
      ...rule({ kind: "drop_streams", rationale: "noisy\nhealth // checks */" }),
      impact: { bytesBefore: 5 * 1024 ** 3, bytesAfter: 0, streamsBefore: 12, streamsAfter: 0, exact: true, measuredAt: now.toISOString() },
    }
    const { text, warnings } = compileAlloyLogs([withImpact], { now, range: "24h" })
    expect(text).toContain("// Generated by Cardinal on 2026-09-26: 1 log rule for Grafana Alloy.")
    expect(text).toContain("// Estimated savings: 5.0 GiB per 24h.")
    expect(text).toContain('loki.process "cardinal" {')
    expect(text).toContain("forward_to = [loki.write.default.receiver]")
    expect(text).toContain("// Why: noisy health // checks */")
    expect(text).toContain("// Saves ~5.0 GiB per 24h, 12 streams (measured)")
    expect(text).toContain('selector            = "{app=\\"api\\"}"')
    expect(text).toContain('action              = "drop"')
    expect(text).toContain('drop_counter_reason = "cardinal_drop_streams"')
    expect(warnings).toEqual([])
    // The rationale's newline must not start a new (uncommented) line.
    expect(text.split("\n").filter((line) => line.includes("health"))).toHaveLength(1)
  })

  it("uses the documented stages for every kind", () => {
    const { text } = compileAlloyLogs(collectorRules(), { now })
    expect(text).toContain("stage.match {")
    expect(text).toContain("stage.drop {")
    expect(text).toContain("stage.regex {")
    expect(text).toContain('source              = "level"')
    expect(text).toContain("stage.sampling {")
    expect(text).toContain("rate                = 0.25")
    expect(text).toContain("stage.label_drop {")
    expect(text).toContain('values = ["pod"]')
    expect(text).toContain("stage.structured_metadata {")
    expect(text).toContain('trace_id = "",')
    // Drops come before label changes.
    expect(text.indexOf("stage.structured_metadata")).toBeGreaterThan(text.lastIndexOf("stage.sampling"))
    expect(text.lastIndexOf("stage.label_drop")).toBeGreaterThan(text.indexOf("stage.structured_metadata"))
  })

  it("escapes values for Alloy strings", () => {
    const { text } = compileAlloyLogs([rule({ kind: "drop_streams", selector: sel(["app", "=", 'a"b\\c']) })], { now })
    // LogQL escaping first (a\"b\\c), then Alloy string escaping on top.
    expect(text).toContain('selector            = "{app=\\"a\\\\\\"b\\\\\\\\c\\"}"')
    const root = parseAlloyBlocks(text)
    const match = root.blocks[0].blocks[0]
    expect(match.attrs.selector).toBe('{app="a\\"b\\\\c"}')
  })

  it("skips retention and shadowed rules with warnings", () => {
    const broad = rule({ kind: "drop_streams", selector: sel(["app", "=", "api"]) })
    const narrow = rule({ kind: "drop_label", selector: sel(["app", "=", "api"], ["env", "=", "x"]), label: "pod" })
    const retention = rule({ kind: "retention", days: 7 })
    const proposed = rule({ kind: "drop_label", label: "node", status: "proposed" })
    const { text, warnings } = compileAlloyLogs([broad, narrow, retention, proposed], { now })
    expect(warnings.some((w) => /retention is not a Alloy stage/.test(w))).toBe(true)
    expect(warnings.some((w) => /already covered by "Drop streams/.test(w))).toBe(true)
    expect(text).not.toContain('"pod"')
    expect(text).not.toContain('"node"')
  })

  it("skips label_to_metadata below Loki 3 and warns when the version is unknown", () => {
    const move = rule({ kind: "label_to_metadata", label: "trace_id" })
    expect(compileAlloyLogs([move], { now, lokiVersion: "2.9.4" }).warnings.join()).toMatch(/Loki 3.0 or later/)
    expect(compileAlloyLogs([move], { now, lokiVersion: "2.9.4" }).text).toContain("No log rules")
    expect(compileAlloyLogs([move], { now }).warnings.join()).toMatch(/allow_structured_metadata/)
    expect(compileAlloyLogs([move], { now, lokiVersion: "v3.1.0" }).warnings).toEqual([])
  })

  it("warns about service_name selectors and unscoped line samples", () => {
    const warnings = compileAlloyLogs(
      [
        rule({ kind: "drop_streams", selector: sel(["service_name", "=", "api"]) }),
        rule({ kind: "sample", selector: sel(), line: { regex: "x" }, keep: 0.5 }),
      ],
      { now }
    ).warnings
    expect(warnings.some((w) => /service_name/.test(w))).toBe(true)
    expect(warnings.some((w) => /needs a selector/.test(w))).toBe(true)
  })

  it("round-trips every collector kind", () => {
    const rules = collectorRules()
    const { text } = compileAlloyLogs(rules, { now })
    const imported = parseAlloyLogs(text)
    expect(imported.warnings).toEqual([])
    expect(keys(imported.rules)).toEqual(keys(rules))
    expect(settings(imported.rules)).toEqual(settings(rules))
    expect(imported.rules.every((r) => r.origin === "import" && r.status === "active")).toBe(true)
  })

  it("imports hand-written Alloy and warns on the rest", () => {
    const text = `
      // comment with { brace
      loki.process "logs" {
        forward_to = [loki.write.default.receiver]
        stage.json {
          expressions = { level = "lvl" }
        }
        stage.match {
          selector = "{app=\\"api\\"} |= \\"GET /metrics\\""
          action   = "drop"
        }
        stage.match {
          selector = "{app=\\"api\\"}"
          stage.drop {
            source = "level"
            value  = "DEBUG"
          }
          stage.drop {
            older_than = "24h"
          }
          stage.match {
            selector = "{env=\\"dev\\"}"
            stage.sampling { rate = 0.2 }
          }
        }
        stage.structured_metadata {
          values = { pod = "pod_name" }
        }
        stage.label_drop { values = ["filename", "stream"] }
      }`
    const { rules, warnings } = parseAlloyLogs(text)
    expect(rules.map((r) => r.kind).sort()).toEqual(["drop_label", "drop_label", "drop_lines", "drop_lines", "sample"])
    const metrics = rules.find((r) => r.kind === "drop_lines" && r.line.regex)
    expect(metrics?.kind === "drop_lines" && metrics.line.regex).toBe("GET /metrics")
    const level = rules.find((r) => r.kind === "drop_lines" && r.line.levels)
    expect(level?.kind === "drop_lines" && level.line.levels).toEqual(["debug"])
    const sample = rules.find((r) => r.kind === "sample")
    expect(sample?.selector.matchers.map((m) => m.label)).toEqual(["app", "env"])
    expect(warnings.some((w) => /stage\.json/.test(w))).toBe(true)
    expect(warnings.some((w) => /older_than/.test(w))).toBe(true)
    expect(warnings.some((w) => /renamed/.test(w))).toBe(true)
  })

  it("rejects injected values on import", () => {
    const { rules, warnings } = parseAlloyLogs('stage.match {\n selector = "{app=\\"a\\nb\\"}"\n action = "drop"\n}')
    expect(rules).toEqual([])
    expect(warnings.join()).toMatch(/control characters/)
    expect(parseAlloyLogs("nothing here").warnings).toEqual(["No loki.process stages found."])
  })
})

describe("Promtail pipeline_stages export", () => {
  it("renders valid YAML with documented stage names", () => {
    const { text, warnings } = compilePromtailLogs(collectorRules(), { now })
    expect(text).toMatch(/^# Generated by Cardinal on 2026-09-26/)
    const doc = parse(text) as { pipeline_stages: Array<Record<string, unknown>> }
    const names = new Set(doc.pipeline_stages.flatMap((stage) => Object.keys(stage)))
    expect([...names].sort()).toEqual(["drop", "labeldrop", "match"])
    const nested = doc.pipeline_stages.flatMap((stage) => {
      const match = stage.match as { stages?: Array<Record<string, unknown>> } | undefined
      return (match?.stages ?? []).flatMap((child) => Object.keys(child))
    })
    expect(new Set(nested)).toEqual(new Set(["drop", "regex", "sampling", "labeldrop", "structured_metadata"]))
    expect(text).toContain("trace_id:")
    expect(text).not.toContain("trace_id: null")
    expect(warnings.some((w) => /allow_structured_metadata/.test(w))).toBe(true)
    const first = doc.pipeline_stages[0].match as Record<string, string>
    expect(first).toMatchObject({ action: "drop", drop_counter_reason: "cardinal_drop_streams" })
    expect(first.selector).toBe('{app="say \\"hi\\"\\\\x", env=~"dev|test"}')
  })

  it("keeps comments single-line", () => {
    const { text } = compilePromtailLogs([rule({ kind: "drop_streams", rationale: "a\nb: c\r\n- d" })], { now })
    expect(text).toContain("# Why: a b: c - d")
    expect(parse(text).pipeline_stages).toHaveLength(1)
  })

  it("round-trips every collector kind", () => {
    const rules = collectorRules()
    const imported = parsePromtailLogs(compilePromtailLogs(rules, { now }).text)
    expect(imported.warnings).toEqual([])
    expect(keys(imported.rules)).toEqual(keys(rules))
    expect(settings(imported.rules)).toEqual(settings(rules))
  })

  it("imports from a full promtail.yml and bare lists", () => {
    const yaml = `
scrape_configs:
  - job_name: app
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{app="api"} !~ "keep"'
          action: drop
      - match:
          selector: '{app="api"}'
          stages:
            - drop:
                expression: "health"
            - sampling:
                rate: 0.3
      - labeldrop: [pod]
`
    const { rules, warnings } = parsePromtailLogs(yaml)
    // A negative line filter on a dropping match is a keep: the drop leaves those lines alone.
    expect(rules.map((r) => r.kind).sort()).toEqual(["drop_label", "drop_lines", "drop_streams", "keep", "sample"])
    expect(rules.find((r) => r.kind === "keep")).toMatchObject({ line: { regex: "keep" }, selector: { matchers: [{ label: "app", op: "=", value: "api" }] } })
    expect(warnings.some((w) => /docker/.test(w))).toBe(true)
    expect(parsePromtailLogs("- sampling:\n    rate: 0.5").rules[0]).toMatchObject({ kind: "sample", keep: 0.5 })
    expect(parsePromtailLogs("a: [").warnings[0]).toMatch(/Not valid YAML/)
  })
})

describe("Loki limits export", () => {
  it("renders retention_stream entries with priorities and notes", () => {
    const rules = [
      rule({ kind: "retention", selector: sel(["namespace", "=", "dev"]), days: 7 }),
      rule({ kind: "retention", selector: sel(["namespace", "=", "dev"], ["app", "=", 'q"x']), days: 1 }),
      rule({ kind: "drop_label", label: "pod" }),
    ]
    const { text, warnings } = compileLokiLimits(rules, { now })
    const doc = parse(text) as { limits_config: { retention_stream: Array<Record<string, unknown>> } }
    expect(doc.limits_config.retention_stream).toEqual([
      { selector: '{namespace="dev"}', priority: 1, period: "168h" },
      { selector: '{app="q\\"x", namespace="dev"}', priority: 2, period: "24h" },
    ])
    expect(text).toContain("retention_enabled")
    expect(text).toContain("overrides.<tenant>")
    expect(warnings.some((w) => /only retention rules/.test(w))).toBe(true)
  })

  it("renders a per-tenant override", () => {
    const { text } = compileLokiLimits([rule({ kind: "retention", days: 3 })], { now, tenant: "29" })
    expect(parse(text)).toEqual({ overrides: { "29": { retention_stream: [{ selector: '{app="api"}', priority: 1, period: "72h" }] } } })
    expect(text).toContain("replaces the global retention_stream list")
  })

  it("round-trips retention rules", () => {
    const rules = [rule({ kind: "retention", days: 30 }), rule({ kind: "retention", selector: sel(["env", "=~", "dev|qa"]), days: 2 })]
    const imported = parseLokiLimits(compileLokiLimits(rules, { now }).text)
    expect(imported.warnings).toEqual([])
    expect(settings(imported.rules)).toEqual(settings(rules))
  })

  it("parses durations and warns on bad entries", () => {
    expect(durationHours("168h")).toBe(168)
    expect(durationHours("1w2d")).toBe(216)
    expect(durationHours("abc")).toBeNull()
    const { rules, warnings } = parseLokiLimits(`
overrides:
  "1":
    retention_stream:
      - selector: '{a="b"}'
        priority: 1
        period: 36h
      - selector: '{a="b"} |= "x"'
        period: 48h
      - selector: '{a="c"}'
        period: 1h
`)
    expect(rules).toHaveLength(1)
    expect(rules[0]).toMatchObject({ kind: "retention", days: 2 })
    expect(warnings).toHaveLength(3)
  })
})

describe("Adaptive Logs export", () => {
  it("compiles drops, level drops and samples to documented drop rules", () => {
    const rules = [
      rule({ kind: "drop_streams", rationale: "unused" }),
      rule({ kind: "drop_lines", selector: sel(["app", "=", "worker"]), line: { levels: ["debug"] } }),
      rule({ kind: "drop_lines", selector: sel(["app", "=", "web"]), line: { regex: "GET /healthz" } }),
      rule({ kind: "sample", selector: sel(["app", "=", "db"]), keep: 0.3 }),
      rule({ kind: "drop_lines", selector: sel(["app", "=", "x"]), line: { regex: "a|b" } }),
      rule({ kind: "drop_lines", selector: sel(["app", "=", "y"]), line: { regex: "^start" } }),
      rule({ kind: "drop_label", label: "pod" }),
      rule({ kind: "retention", days: 3 }),
    ]
    const { dropRules, warnings, text } = compileAdaptiveLogs(rules, { now })
    expect(JSON.parse(text)).toEqual(dropRules)
    expect(dropRules.map((r) => r.body)).toEqual([
      { stream_selector: '{app="api"}', drop_rate: 100 },
      { stream_selector: '{app="worker"}', drop_rate: 100, levels: ["debug"] },
      { stream_selector: '{app="web"}', drop_rate: 100, log_line_contains: ["GET /healthz"] },
      { stream_selector: '{app="db"}', drop_rate: 70 },
    ])
    expect(dropRules[0]).toMatchObject({ segment_id: "__global__", version: 1, disabled: false, name: 'Drop streams {app="api"}' })
    expect(warnings.filter((w) => /not regexes/.test(w))).toHaveLength(2)
    expect(warnings.some((w) => /drop label pod/i.test(w))).toBe(true)
    expect(warnings.some((w) => /retention/.test(w))).toBe(true)
    expect(adaptiveLogsInstructions({ dropRules, exemptions: [] })).toContain("Drop rate: 70%")
  })

  it("recognises hosted Loki URLs only", async () => {
    const { adaptiveLogsBaseUrl, recommendationPattern } = await loadAdaptiveLogs()
    expect(adaptiveLogsBaseUrl("https://logs-prod-012.grafana.net/loki/api/v1")).toBe("https://logs-prod-012.grafana.net")
    expect(adaptiveLogsBaseUrl("https://mystack.grafana.net")).toBeNull()
    expect(adaptiveLogsBaseUrl("http://logs-prod-012.grafana.net")).toBeNull()
    expect(adaptiveLogsBaseUrl("https://logs-prod-012.grafana.net.evil.com")).toBeNull()
    expect(adaptiveLogsBaseUrl("not a url")).toBeNull()
    expect(recommendationPattern({ tokens: ["level=info msg=", "<*>"] })).toBe("level=info msg=<*>")
  })
})

describe("compile helpers", () => {
  it("formats bytes and flattens comments", () => {
    expect(formatBytesIEC(0)).toBe("0 B")
    expect(formatBytesIEC(1536)).toBe("1.5 KiB")
    expect(formatBytesIEC(200 * 1024 ** 3)).toBe("200 GiB")
    expect(commentText("a b\nc")).toBe("a b c")
    expect(commentText("x".repeat(400)).length).toBe(300)
  })
})
