import { jobLabel } from "@/lib/core/jobs"
import { formatDelta } from "@/lib/core/savings"
import type { Rule } from "@/lib/core/rules"

// Human-readable descriptions of a rule set: the header comment on exported
// config and the markdown for a pull request description.

/** One line saying what a rule does, e.g. `Drop labels pod, uid from http_requests_total`. */
export function describeRule(rule: Rule, code: (text: string) => string = (text) => text) {
  const metric = code(rule.selector.metric)
  switch (rule.kind) {
    case "drop_metric":
      return `Drop metric ${metric}`
    case "drop_labels":
      return `Drop label${rule.labels.length === 1 ? "" : "s"} ${rule.labels.map(code).join(", ")} from ${metric}`
    case "drop_series":
      return `Drop series of ${metric} where ${code(`${rule.match.label}=~"${rule.match.regex}"`)}`
    case "keep_buckets":
      return `Keep only le buckets ${rule.buckets.map(code).join(", ")} of ${metric}`
  }
}

export function scopeLabel(rule: Pick<Rule, "selector">) {
  return rule.selector.job === undefined ? "all jobs" : `job ${jobLabel(rule.selector.job)}`
}

/** Series a rule removes, from its measured impact; null when not measured. */
export function ruleSavedSeries(rule: Rule) {
  return rule.impact ? Math.max(0, rule.impact.seriesBefore - rule.impact.seriesAfter) : null
}

// Newlines (or other control characters) in a rationale or job name must not
// end a comment line and turn the rest into config.
// eslint-disable-next-line no-control-regex
const oneLine = (text: string) => text.replace(/[\u0000-\u001f\u007f\u2028\u2029]+/g, " ").trim()

export interface ReportContext {
  generatedAt: Date
  totalSeries: number
  savedSeries: number
  isEstimate: boolean
  /** Monthly cost of a series count, or null without a configured price. */
  cost?: (series: number) => number | null
  formatCost?: (amount: number) => string
  /** Short usage evidence per metric, e.g. "2 alerts · 3 dashboards"; missing = not checked. */
  usage?: Record<string, string | null | undefined>
}

function totals(context: ReportContext) {
  const percent = context.totalSeries > 0 ? ((context.savedSeries / context.totalSeries) * 100).toFixed(1) : null
  const approx = context.isEstimate ? "~" : ""
  const cost = context.cost?.(context.savedSeries)
  const costText = cost != null && context.formatCost ? `, about ${context.formatCost(cost)}/month` : ""
  return `${approx}${context.savedSeries.toLocaleString()} active series${percent ? ` (${percent}% of ${context.totalSeries.toLocaleString()})` : ""}${costText}`
}

/** Comment lines (without the comment marker) heading exported config. */
export function headerLines(rules: Rule[], context: ReportContext): string[] {
  const lines = [
    `Generated by Cardinal on ${context.generatedAt.toISOString().slice(0, 16).replace("T", " ")} UTC.`,
    `${rules.length} rule${rules.length === 1 ? "" : "s"}, expected to remove ${totals(context)}.`,
  ]
  if (rules.length) lines.push("")
  for (const rule of rules) {
    const saved = ruleSavedSeries(rule)
    const savedText = saved === null ? "not measured" : `${formatDelta(-saved)} series`
    lines.push(oneLine(`- ${describeRule(rule)} (${scopeLabel(rule)}): ${savedText}.`))
    if (rule.rationale) lines.push(oneLine(`  Why: ${rule.rationale}`))
  }
  return lines
}

/** The header as a comment block: `#` for YAML, `//` for Alloy. */
export function renderHeader(rules: Rule[], context: ReportContext, marker: "#" | "//") {
  return `${headerLines(rules, context)
    .map((line) => (line ? `${marker} ${line}` : marker))
    .join("\n")}\n\n`
}

const cell = (text: string) => oneLine(text).replace(/\|/g, "\\|")
/** Inline code that survives backticks in the text. */
const md = (text: string) => {
  const fence = text.includes("`") ? "``" : "`"
  return `${fence}${fence === "``" ? " " : ""}${oneLine(text)}${fence === "``" ? " " : ""}${fence}`
}

/** Markdown for a pull request: a rules table and each rule's rationale. */
export function prDescription(rules: Rule[], context: ReportContext & { target: string }) {
  const priced = context.cost?.(1) != null
  const header = ["Rule", "Scope", "Series saved", ...(priced ? ["Cost / month"] : []), "Usage evidence"]
  const rows = rules.map((rule) => {
    const saved = ruleSavedSeries(rule)
    const cost = saved === null ? null : context.cost?.(saved)
    const usage = context.usage?.[rule.selector.metric]
    return [
      cell(describeRule(rule, md)),
      cell(scopeLabel(rule)),
      saved === null ? "not measured" : formatDelta(-saved),
      ...(priced ? [cost != null && context.formatCost ? context.formatCost(cost) : "–"] : []),
      cell(usage === undefined ? "not checked" : (usage ?? "none found")),
    ]
  })
  const table = [
    `| ${header.join(" | ")} |`,
    `| ${header.map((_, index) => (index >= 2 && index < header.length - 1 ? "---:" : "---")).join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ]
  const rationale = rules
    .filter((rule) => rule.rationale)
    .map((rule) => `- **${describeRule(rule, md)}** (${scopeLabel(rule)}): ${oneLine(rule.rationale ?? "")}`)

  return [
    "## Reduce metric cardinality",
    "",
    `${rules.length} ${context.target} rule${rules.length === 1 ? "" : "s"} generated with Cardinal on ${context.generatedAt.toISOString().slice(0, 10)}. Expected to remove ${totals(context)}.`,
    "",
    ...table,
    "",
    "### Rationale",
    "",
    ...(rationale.length ? rationale : ["_No rationale recorded for these rules._"]),
    "",
    "Usage evidence covers Prometheus alerting and recording rules, plus Grafana Cloud dashboards and queries when connected to Grafana Cloud. Dashboards elsewhere were not checked.",
    "",
  ].join("\n")
}

/** "just now", "12 min ago", "3 h ago", "2 days ago". */
export function formatAgo(iso: string | undefined, now = Date.now()) {
  const at = iso ? Date.parse(iso) : Number.NaN
  if (!Number.isFinite(at)) return null
  const minutes = Math.floor(Math.max(0, now - at) / 60_000)
  if (minutes < 1) return "just now"
  if (minutes < 60) return `${minutes} min ago`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours} h ago`
  const days = Math.floor(hours / 24)
  return `${days} day${days === 1 ? "" : "s"} ago`
}
