import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs"
import path from "node:path"

import packageJson from "../package.json"
import { SKIPPED_ASSETS } from "./static"

// Compiles the `cardinal` server into single-file executables with the app
// (dist/client, from `bun run build`) embedded. Bun embeds files imported
// `with { type: "file" }`, so this writes an entry that imports every file.
//
//   bun relay/build.ts                      all targets into relay/dist/
//   bun relay/build.ts bun-darwin-arm64     one target
//   bun relay/build.ts [target] --outfile x one target (default: this machine), custom path (Docker)

const TARGETS = ["bun-linux-x64", "bun-linux-arm64", "bun-darwin-arm64", "bun-darwin-x64", "bun-windows-x64"] as const

const root = path.resolve(import.meta.dir, "..")
const client = path.join(root, "dist/client")
const outDir = path.join(import.meta.dir, "dist")
const buildDir = path.join(outDir, ".build")
const version = process.env.CARDINAL_VERSION?.replace(/^v/, "") || packageJson.version

function listFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name)
    return entry.isDirectory() ? listFiles(full) : entry.isFile() ? [full] : []
  })
}

function writeEntry() {
  if (!statSync(path.join(client, "index.html"), { throwIfNoEntry: false })) {
    throw new Error("dist/client/index.html is missing; run `bun run build` first")
  }
  const files = listFiles(client)
    .map((file) => ({ file, url: `/${path.relative(client, file).split(path.sep).join("/")}` }))
    .filter(({ url }) => !SKIPPED_ASSETS.has(url))
  const imports = files.map(({ file }, index) => `import f${index} from ${JSON.stringify(path.relative(buildDir, file).split(path.sep).join("/"))} with { type: "file" }`)
  const entries = files.map(({ url }, index) => `  [${JSON.stringify(url)}, Bun.file(f${index})],`)
  const source = [
    "// Generated by relay/build.ts",
    `import { start } from ${JSON.stringify(path.relative(buildDir, path.join(import.meta.dir, "main.ts")).split(path.sep).join("/"))}`,
    ...imports,
    "",
    "const assets = new Map<string, Blob>([",
    ...entries,
    "])",
    "",
    `await start({ assets, version: ${JSON.stringify(version)} })`,
    "",
  ].join("\n")
  mkdirSync(buildDir, { recursive: true })
  const entry = path.join(buildDir, "entry.ts")
  writeFileSync(entry, source)
  return { entry, count: files.length }
}

function outfileFor(target: string) {
  const name = `cardinal-${target.replace(/^bun-/, "")}`
  return path.join(outDir, target.includes("windows") ? `${name}.exe` : name)
}

async function compile(entry: string, target: string | undefined, outfile: string) {
  const result = await Bun.build({
    entrypoints: [entry],
    compile: target ? { target: target as Bun.Build.CompileTarget, outfile } : { outfile },
    minify: true,
    sourcemap: "linked",
  })
  if (!result.success) {
    for (const log of result.logs) console.error(log)
    throw new Error(`Build failed for ${target ?? "host"}`)
  }
  console.log(`  ${path.relative(root, outfile)}`)
}

const args = process.argv.slice(2)
const outfileIndex = args.indexOf("--outfile")
const outfile = outfileIndex >= 0 ? args.splice(outfileIndex, 2)[1] : undefined
for (const target of args) {
  if (!(TARGETS as readonly string[]).includes(target)) throw new Error(`Unknown target ${target}; use one of ${TARGETS.join(", ")}`)
}
if ((outfileIndex >= 0 && !outfile) || (outfile !== undefined && args.length > 1)) throw new Error("--outfile takes a path and at most one target")
const { entry, count } = writeEntry()
console.log(`Embedding ${count} files from dist/client (cardinal ${version})`)

try {
  if (outfile !== undefined) {
    await compile(entry, args[0], path.resolve(outfile))
  } else {
    for (const target of args.length ? args : TARGETS) await compile(entry, target, outfileFor(target))
  }
} finally {
  rmSync(buildDir, { recursive: true, force: true })
}
