import { activeLogRules, describeLogRule, logRuleProblem, logRuleProtectedBy, logRuleShadowedBy } from "@/lib/core/logs/rules"
import type { KeepRule, LogRule, LogRuleKind } from "@/lib/core/logs/types"

export interface LogCompileResult {
  text: string
  warnings: string[]
}

export interface LogCompileOptions {
  /** Header date; defaults to now. */
  now?: Date
  /** Loki version of the target, e.g. "2.9.4". label_to_metadata is skipped below 3.0. */
  lokiVersion?: string
  /** How long the measured impacts cover, e.g. "24h", for the savings comments. */
  range?: string
}

/** Stage order: drops first (their selectors may use labels later stages remove), then label moves and drops. */
export const STAGE_ORDER: readonly LogRuleKind[] = [
  "drop_streams",
  "drop_lines",
  "sample",
  "label_to_metadata",
  "drop_label",
  "retention",
  "keep",
]

/** 1024-based byte size, e.g. "1.5 GiB". */
export function formatBytesIEC(bytes: number) {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B"
  const units = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"]
  const exponent = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)))
  const value = bytes / 1024 ** exponent
  return `${exponent === 0 ? Math.round(value) : value.toFixed(value < 10 ? 1 : 0)} ${units[exponent]}`
}

/** Free text made safe for a one-line comment: no control characters, bounded length. */
export function commentText(text: string, max = 300) {
  // eslint-disable-next-line no-control-regex
  const flat = text.replace(/[\u0000-\u001f\u007f\u2028\u2029]+/g, " ").trim()
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat
}

export function lokiMajor(version: string | undefined) {
  const match = /^v?(\d+)\./.exec(version ?? "")
  return match ? Number(match[1]) : undefined
}

export function savedBytes(rule: LogRule) {
  return rule.impact ? Math.max(0, rule.impact.bytesBefore - rule.impact.bytesAfter) : undefined
}

/** Comment lines for one rule: what it does, why, and what it saves. */
export function ruleCommentLines(rule: LogRule, options: LogCompileOptions) {
  const lines = [commentText(describeLogRule(rule))]
  if (rule.rationale) lines.push(`Why: ${commentText(rule.rationale)}`)
  const impact = rule.impact
  if (impact) {
    const bytes = savedBytes(rule) ?? 0
    const streams =
      impact.streamsBefore !== undefined && impact.streamsAfter !== undefined
        ? Math.max(0, impact.streamsBefore - impact.streamsAfter)
        : 0
    const parts = [
      bytes > 0 ? `${formatBytesIEC(bytes)}${options.range ? ` per ${commentText(options.range, 20)}` : ""}` : "",
      streams > 0 ? `${streams.toLocaleString("en-US")} streams` : "",
    ].filter(Boolean)
    if (parts.length) lines.push(`Saves ~${parts.join(", ")} (${impact.exact ? "measured" : "estimate"})`)
    if (impact.note) lines.push(commentText(impact.note))
  }
  return lines
}

export function headerLines(rules: LogRule[], options: LogCompileOptions, target: string) {
  const date = (options.now ?? new Date()).toISOString().slice(0, 10)
  const lines = [`Generated by Cardinal on ${date}: ${rules.length} log rule${rules.length === 1 ? "" : "s"} for ${target}.`]
  const measured = rules.filter((rule) => rule.impact)
  const total = measured.reduce((sum, rule) => sum + (savedBytes(rule) ?? 0), 0)
  if (total > 0) {
    const estimate = measured.some((rule) => !rule.impact!.exact) || measured.length < rules.length
    lines.push(
      `Estimated savings: ${formatBytesIEC(total)}${options.range ? ` per ${commentText(options.range, 20)}` : ""}${estimate ? " (partly estimated)" : ""}.`
    )
  }
  return lines
}

/**
 * The rules a compiler should emit: active, valid and not made redundant by a
 * broader drop or protected entirely by a keep, in stage order. Everything left
 * out gets a warning. Keep rules are not stages: they come back in `keeps`,
 * for the compiler to narrow the drops with (or turn into exemptions).
 */
export function compilableRules(rules: LogRule[], supported: readonly LogRuleKind[], target: string, options: LogCompileOptions = {}) {
  const warnings: string[] = []
  const active = activeLogRules(rules)
  const major = lokiMajor(options.lokiVersion)
  const selected: LogRule[] = []
  const keeps: KeepRule[] = []
  for (const rule of active) {
    const problem = logRuleProblem(rule)
    if (problem) {
      warnings.push(`Skipped "${commentText(describeLogRule(rule), 120)}": ${problem}.`)
      continue
    }
    if (rule.kind === "keep") {
      if (!logRuleShadowedBy(rule, active)) keeps.push(rule)
      continue
    }
    const protectedBy = logRuleProtectedBy(rule, active)
    if (protectedBy) {
      warnings.push(`Skipped "${commentText(describeLogRule(rule), 120)}": keep rule "${commentText(describeLogRule(protectedBy), 120)}" protects every line it would remove.`)
      continue
    }
    if (!supported.includes(rule.kind)) {
      warnings.push(`Skipped "${commentText(describeLogRule(rule), 120)}": ${unsupportedReason(rule.kind, target)}`)
      continue
    }
    if (rule.kind === "label_to_metadata" && major !== undefined && major < 3) {
      warnings.push(`Skipped "${commentText(describeLogRule(rule), 120)}": structured metadata needs Loki 3.0 or later (target is ${options.lokiVersion}).`)
      continue
    }
    const shadow = logRuleShadowedBy(rule, active)
    if (shadow) {
      warnings.push(`Skipped "${commentText(describeLogRule(rule), 120)}": already covered by "${commentText(describeLogRule(shadow), 120)}".`)
      continue
    }
    selected.push(rule)
  }
  if (major === undefined && selected.some((rule) => rule.kind === "label_to_metadata")) {
    warnings.push("Moving labels to structured metadata needs Loki 3.0+ with allow_structured_metadata enabled (the default in 3.x).")
  }
  selected.sort((a, b) => STAGE_ORDER.indexOf(a.kind) - STAGE_ORDER.indexOf(b.kind))
  return { rules: selected, keeps, warnings }
}

function unsupportedReason(kind: LogRuleKind, target: string) {
  if (kind === "retention") return `retention is not a ${target} stage; export it as Loki limits (retention_stream).`
  if (target === "Loki limits") return "only retention rules become Loki limits; export the rest for your collector."
  return `${target} has no equivalent.`
}

export const DROP_REASON = "cardinal"
