import { formatBytes, toGB } from "@/lib/core/bytes"
import { csvField } from "@/lib/core/csv"
import { computeLogSavings } from "@/lib/core/logs/impact"
import { describeLogRule } from "@/lib/core/logs/rules"
import { bytesPerDay, LOGS_RANGE_SECONDS } from "@/lib/core/logs/snapshot"
import type { LogRule, LogsSnapshot } from "@/lib/core/logs/types"

// A shareable summary of the logs snapshot and log rules, as Markdown or CSV:
// the logs twin of features/overview/report.ts, section for section.

export interface LogsReportInput {
  snapshot: LogsSnapshot
  /** store.logRules, read defensively. */
  logRules?: unknown
  /** Price per GB ingested; costs are left out when undefined. */
  pricePerGB?: number
  source?: string
  top?: number
}

const number = (value: number) => value.toLocaleString("en-US")

function money(amount: number) {
  const digits = amount < 100 ? 2 : 0
  return `$${amount.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits })}`
}

function cell(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\n/g, " ")
}

function code(value: string) {
  return `\`${value.replace(/`/g, "'")}\``
}

function asRules(value: unknown): LogRule[] {
  return Array.isArray(value) ? value.filter((rule): rule is LogRule => Boolean(rule && typeof rule === "object" && "kind" in rule && "status" in rule)) : []
}

export function buildLogsMarkdownReport({ snapshot, logRules, pricePerGB, source, top = 15 }: LogsReportInput) {
  const perDay = bytesPerDay(snapshot)
  const rangeDays = LOGS_RANGE_SECONDS[snapshot.range] / 86400
  const rules = asRules(logRules)
  const savings = computeLogSavings(rules, snapshot)
  const savedPerDay = savings.savedBytes / rangeDays
  const priced = pricePerGB !== undefined
  const cost = (bytes: number) => money(toGB(bytes) * pricePerGB!)
  const captured = new Date(snapshot.capturedAt)
  const lines = [
    `# Cardinal logs report${source ? `: ${source}` : ""}`,
    "",
    `Snapshot of the last ${snapshot.range} taken ${Number.isNaN(captured.getTime()) ? "at an unknown time" : `${captured.toISOString().replace("T", " ").slice(0, 16)} UTC`}, grouped by ${code(snapshot.groupLabel)}. Sizes are 1024-based (1 GB = 1,024³ bytes) and come from Loki's index, an estimate.`,
    "",
    "## Summary",
    "",
    `- **Streams:** ${number(snapshot.totals.streams)}`,
    `- **Ingested:** ${formatBytes(snapshot.totals.bytes)} in ${snapshot.range} (${formatBytes(perDay)} a day)${priced ? `, ≈ ${cost(perDay)}/day` : ""}`,
    ...(snapshot.totals.lines ? [`- **Lines:** ${number(snapshot.totals.lines)}`] : []),
    `- **Label names:** ${number(snapshot.totals.labelCount)}`,
    `- **Active rules save:** ${savings.isEstimate ? "~" : ""}${formatBytes(savedPerDay)} a day (${savings.percent.toFixed(1)}%)${priced ? `, ≈ ${cost(savedPerDay)}/day` : ""}`,
    "",
    `## Top ${snapshot.groupLabel} values by volume`,
    "",
    "| # | Value | Bytes | Share | Streams |",
    "|---:| --- | ---: | ---: | ---: |",
    ...snapshot.groups.slice(0, top).map((group, index) => `| ${index + 1} | ${cell(group.value)} | ${formatBytes(group.bytes)} | ${group.share.toFixed(1)}% | ${number(group.streams)} |`),
    "",
    "## Labels by distinct values",
    "",
    "| Label | Distinct values | ID-like |",
    "| --- | ---: | --- |",
    ...snapshot.labels.slice(0, top).map((label) => `| ${code(label.label)} | ${number(label.distinctValues)} | ${label.idLike ? "yes" : ""} |`),
    "",
    "## Rules",
    "",
  ]
  const active = rules.filter((rule) => rule.status === "active")
  const proposed = rules.filter((rule) => rule.status === "proposed")
  if (!active.length && !proposed.length) lines.push("No rules yet.", "")
  for (const [title, list] of [
    ["Active", active],
    ["Proposed", proposed],
  ] as const) {
    if (!list.length) continue
    lines.push(`### ${title}`, "", `| Rule | Ingest saved |${priced ? " Cost saved |" : ""}`, `|---|---:|${priced ? "---:|" : ""}`)
    for (const rule of list) {
      const impact = rule.impact
      const saved = impact ? Math.max(0, impact.bytesBefore - impact.bytesAfter) / rangeDays : null
      const approx = impact && !impact.exact ? "~" : ""
      const savedText =
        saved === null ? "not measured" : rule.kind === "keep" ? "keeps lines" : rule.kind === "retention" ? "storage only" : `${approx}${formatBytes(saved)}/day`
      const costText = priced ? (saved ? ` ≈ ${cost(saved)}/day |` : " |") : ""
      lines.push(`| ${cell(describeLogRule(rule))} | ${savedText} |${costText}`)
    }
    lines.push("")
  }
  if (savings.isEstimate) lines.push("_Totals marked ~ include estimates (levels, sampling, overlapping selectors or kept lines) or rules not measured yet._", "")
  lines.push("_Generated by Cardinal._", "")
  return lines.join("\n")
}

/** Every group in the snapshot: value, bytes, share and streams. */
export function buildLogsCsv(snapshot: LogsSnapshot) {
  const rows = [
    [snapshot.groupLabel, "bytes", "share_percent", "streams"].map(csvField).join(","),
    ...snapshot.groups.map((group) => [group.value, group.bytes, group.share.toFixed(2), group.streams].map(csvField).join(",")),
  ]
  return `${rows.join("\n")}\n`
}
